package hu.mas.core.agent.message;

public enum MessageType {

	ROUTE_INFO_REQUEST, ROUTE_SELECTION_REQUEST, ROUTE_RECOMMENDATION, ROUTE_SELECTION_ANSWER, ROUTE_STARTED_REQUEST,
	ROUTE_STARTED_ANSWER, RE_ROUTE_STARTED_REQUEST, RE_ROUTE_STARTED_ANSWER;

}
