package hu.mas.core.agent.message;

public enum MessageType {

	ROUTE_INFO_REQUEST, ROUTE_SELECTION_REQUEST, ROUTE_RECOMMENDATION, ROUTE_SELECTION_ANSWER, LOCATION_INFO_REQUEST,
	LOCATION_INFO_ANSWER, RE_ROUTE_REQUEST, RE_ROUTE_ANSWER;

}
