package hu.mas.core.mas.model.message;

public enum MessageType {

	ROUTE_INFO_REQUEST, ROUTE_SELECTION_REQUEST, ROUTE_RECOMMENDATION, ROUTE_SELECTION_ANSWER, ROUTE_STARTED_REQUEST,
	ROUTE_STARTED_ANSWER, MAS_TERMINATED;

}
