package hu.mas.core.mas;

public enum Mas {

	NO_INTENTION_SUMO_DELEGATED_MAS, NO_INTENTION_TRAVEL_TIME_MAS, DETAILED_INTENTION_TRAVEL_TIME_MAS,
	DETAILED_INTENTION_ROUTING_SPEED_MAS, SIMPLE_INTENTION_TRAVEL_TIME_MAS, SIMPLE_INTENTION_ROUTING_SPEED_MAS;

}
